language: node_js

node_js:
  - '8'

install:
  - npm install

script:
  - npm -v
  - npm run build

env:
  - CXX=g++-4.8

cache:
  directories:
    - 'node_modules'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  local-dir: build
  on:
    branch: master
